### PR TITLE
convert and expand entries to correctly show and select fields

### LINKED ISSUE #355: Print view malfunction
image
Print view is not working well.
The checkboxes of all available fields are not there and the images are lost.

### PR DESCRIPTION
**Pull request by Danble**
#### Relevant Issue
(prepend "closes" if issue will be closed by PR)
closes #355 

#### Summarize what changed in this PR (for developers)
I modified the PrintFieldCheckboxes component using the convert_and_expand_entry function and changed the logic of the fieldsThatExist dynamic variable.

#### How can the changes be tested? 
Please also provide applicable links using relative paths from root (e.g. `/apatani/entries`) and reviewers can just add that onto preview urls or localhost.
/muniche/entries/print

#### Checklist before marking ready to merge
Please keep it in draft mode until these are completed:
- [ ] Equal time was spent cleaning the code as writing it (Boy Scout Rule)
  - [ ] Functions
    - [ ] Functions that don't belong in Svelte components are extracted out into `.ts` files
    - [ ] Functions are short and well named
    - [ ] Concise tests are written for all functions
  - [ ] Classes (a Svelte Component is a Class)
    - [ ] Svelte components are broken down into smaller components so that each component is responsible for one thing (Single Responsibility Principle)
    - [ ] Stories/variants are written to describe use cases
  - [ ] Comments are only included when absolutely necessary information that cannot be explained in code is needed

### CODE REVIEW

File: packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte [hunk 1]
```diff
@@ -2,21 +2,23 @@
...
   $: fieldsThatExist = Object.keys($preferredPrintFields).filter((field) => {
-    if (field === 'gloss') return true;
     return entries.find((entry) => {
-      if (field === 'alternateOrthographies')
-        return entry.local_orthography_1 || entry.local_orthography_2 || entry.local_orthography_3 || entry.local_orthography_4 || entry.local_orthography_5;
-      if (field === 'example_sentence') return entry.senses?.[0].example_sentences?.length;
-      if (field === 'sdn') return entry.senses?.[0].ld_semantic_domains_keys?.length;
-      if (field === 'image') return entry.senses?.[0].photo_files?.length;
-      if (field === 'speaker') return entry.sound_files?.[0].speakerName || entry.sound_files?.[0].speaker_ids?.length;
+      entry = convert_and_expand_entry(entry);
```
Comment (jacob-8) [inline packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte:14]: Heed the types - this component's entries should already be expanded before coming in as you can see from the type. As you can see from https://github.com/livingtongues/living-dictionaries/blob/fix-print-view/packages/site/src/routes/%5BdictionaryId%5D/entries/print/%2Bpage.svelte#L127 it's the +page.svelte file's responsibility to provide expanded entries. Please update https://github.com/livingtongues/living-dictionaries/blob/fix-print-view/packages/site/src/routes/%5BdictionaryId%5D/entries/print/%2Bpage.svelte#L109 to `<PrintFieldCheckboxes entries={entries.map(convert_and_expand_entry)} {preferredPrintFields} {showLabels} {showQrCode} />`

File: packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte [hunk 2]
```diff
@@ -2,21 +2,23 @@
...
   import { t } from 'svelte-i18n';
   import { StandardPrintFields, type ExpandedEntry, type IPrintFields } from '@living-dictionaries/types';
+  import { convert_and_expand_entry } from '$lib/transformers/convert_and_expand_entry';
 
   export let entries: ExpandedEntry[];
   export let preferredPrintFields: Readable<IPrintFields>;
   export let showLabels: Readable<boolean>;
   export let showQrCode: Readable<boolean>;
 
   $: fieldsThatExist = Object.keys($preferredPrintFields).filter((field) => {
```
Comment (jacob-8) [inline packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte:12]: Please revert all changes to this file, as we want the gloss field always set to true. I realized we can get typing to work here by updating this line to `$: fieldsThatExist = (Object.keys($preferredPrintFields) as (keyof IPrintFields)[]).filter((field) => {` so please do that while you're already in here.

**Review by jacob-8 — CHANGES_REQUESTED** [review]

File: packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte (hunk 2 above)
Comment (jacob-8) [reply packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte:12]: Somehow this comment didn't get put on the right line (12) but I think you can understand it still.

File: packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte (hunk 1 above)
Comment (Danble) [reply packages/site/src/routes/[dictionaryId]/entries/print/PrintFieldCheckboxes.svelte:14]: You're rigth! Sorry! I misundertood the problem

**Review by jacob-8 — APPROVED** [review]
